basePath: /
definitions:
  models.ChatCompletionRequest:
    properties:
      max_tokens:
        type: integer
      messages:
        items:
          $ref: '#/definitions/models.ChatMessage'
        type: array
      temperature:
        type: number
      user_id:
        type: string
    type: object
  models.ChatCompletionResponse:
    properties:
      model:
        type: string
      response:
        type: string
      timestamp:
        type: string
      user_id:
        type: string
    type: object
  models.ChatMessage:
    properties:
      content:
        type: string
      role:
        type: string
    type: object
  models.CompleteRequest:
    properties:
      max_tokens:
        type: integer
      prompt:
        type: string
      temperature:
        type: number
      user_id:
        type: string
    type: object
  models.CompleteResponse:
    properties:
      model:
        type: string
      response:
        type: string
      timestamp:
        type: string
      user_id:
        type: string
    type: object
  models.ErrorResponse:
    properties:
      code:
        type: integer
      error:
        type: string
      message:
        type: string
    type: object
  models.GenerateRequest:
    properties:
      max_tokens:
        type: integer
      prompt:
        type: string
      temperature:
        type: number
      user_id:
        type: string
    type: object
  models.GenerateResponse:
    properties:
      model:
        type: string
      response:
        type: string
      timestamp:
        type: string
      user_id:
        type: string
    type: object
  models.HealthResponse:
    properties:
      status:
        type: string
      timestamp:
        type: string
      version:
        type: string
    type: object
info:
  contact:
    email: support@example.com
    name: API Support
    url: https://github.com/Ammar0144/ai/issues
  description: A comprehensive Go-based AI service providing various artificial intelligence
    capabilities with advanced rate limiting, CORS support, and robust error handling.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: https://github.com/Ammar0144/ai
  title: AI Service API
  version: 1.0.0
paths:
  /ai/chat/completions:
    post:
      consumes:
      - application/json
      description: Generate a chat completion based on conversation history. Rate
        limited to 30 requests per minute per IP address.
      parameters:
      - description: Chat completion request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.ChatCompletionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Successful chat completion
          schema:
            $ref: '#/definitions/models.ChatCompletionResponse'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "429":
          description: Rate limit exceeded
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Chat completion
      tags:
      - AI Processing
  /ai/complete:
    post:
      consumes:
      - application/json
      description: Complete text based on a given prompt. Rate limited to 30 requests
        per minute per IP address.
      parameters:
      - description: Complete request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.CompleteRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Successful text completion
          schema:
            $ref: '#/definitions/models.CompleteResponse'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "429":
          description: Rate limit exceeded
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Text completion
      tags:
      - AI Processing
  /ai/generate:
    post:
      consumes:
      - application/json
      description: Generate text based on a given prompt. Rate limited to 30 requests
        per minute per IP address.
      parameters:
      - description: Generate request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.GenerateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Successful text generation
          schema:
            $ref: '#/definitions/models.GenerateResponse'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "429":
          description: Rate limit exceeded
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Text generation
      tags:
      - AI Processing
  /ai/model-info:
    get:
      description: Get detailed information about the current AI model being used.
        Rate limited to 100 requests per minute per IP address.
      produces:
      - application/json
      responses:
        "200":
          description: Model information
          schema:
            additionalProperties: true
            type: object
        "429":
          description: Rate limit exceeded
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get model information
      tags:
      - System
  /health:
    get:
      description: Check the health status of the AI service. Rate limited to 200
        requests per minute per IP address.
      produces:
      - application/json
      responses:
        "200":
          description: Service is healthy
          schema:
            $ref: '#/definitions/models.HealthResponse'
        "429":
          description: Rate limit exceeded
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Health check
      tags:
      - System
swagger: "2.0"
