definitions:
  models.ChatCompletionRequest:
    properties:
      max_tokens:
        type: integer
      messages:
        items:
          $ref: '#/definitions/models.ChatMessage'
        type: array
      temperature:
        type: number
      user_id:
        type: string
    type: object
  models.ChatCompletionResponse:
    properties:
      model:
        type: string
      response:
        type: string
      timestamp:
        type: string
      user_id:
        type: string
    type: object
  models.ChatMessage:
    properties:
      content:
        type: string
      role:
        type: string
    type: object
  models.ClassificationRequest:
    properties:
      categories:
        items:
          type: string
        type: array
      text:
        type: string
      user_id:
        type: string
    type: object
  models.ClassificationResponse:
    properties:
      classification:
        type: string
      timestamp:
        type: string
      user_id:
        type: string
    type: object
  models.EmbeddingsRequest:
    properties:
      text:
        type: string
      user_id:
        type: string
    type: object
  models.EmbeddingsResponse:
    properties:
      embeddings:
        type: string
      timestamp:
        type: string
      user_id:
        type: string
    type: object
  models.ErrorResponse:
    properties:
      code:
        type: integer
      error:
        type: string
      message:
        type: string
    type: object
  models.HealthResponse:
    properties:
      status:
        type: string
      timestamp:
        type: string
      version:
        type: string
    type: object
  models.MessageRequest:
    properties:
      message:
        type: string
      user_id:
        type: string
    required:
    - message
    type: object
  models.MessageResponse:
    properties:
      model:
        type: string
      response:
        type: string
      timestamp:
        type: string
      user_id:
        type: string
    type: object
  models.QuestionRequest:
    properties:
      question:
        type: string
      user_id:
        type: string
    required:
    - question
    type: object
  models.SentimentRequest:
    properties:
      text:
        type: string
      user_id:
        type: string
    type: object
  models.SentimentResponse:
    properties:
      sentiment:
        type: string
      timestamp:
        type: string
      user_id:
        type: string
    type: object
  models.SummarizationRequest:
    properties:
      max_length:
        type: integer
      text:
        type: string
      user_id:
        type: string
    type: object
  models.SummarizationResponse:
    properties:
      summary:
        type: string
      timestamp:
        type: string
      user_id:
        type: string
    type: object
info:
  contact: {}
paths:
  /ai/ask:
    post:
      consumes:
      - application/json
      description: Send a question to the AI and get a cleaned, intelligent response.
        Rate limited to 30 requests per minute per IP address.
      parameters:
      - description: Question request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.QuestionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Q&A response
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "429":
          description: Rate limit exceeded
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Ask a question
      tags:
      - Q&A
  /ai/chat/completions:
    post:
      consumes:
      - application/json
      description: Generate a chat completion based on conversation history. Rate
        limited to 30 requests per minute per IP address.
      parameters:
      - description: Chat completion request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.ChatCompletionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Successful chat completion
          schema:
            $ref: '#/definitions/models.ChatCompletionResponse'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "429":
          description: Rate limit exceeded
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Chat completion
      tags:
      - AI Processing
  /ai/classifications:
    post:
      consumes:
      - application/json
      description: Classify text into predefined categories. Rate limited to 30 requests
        per minute per IP address.
      parameters:
      - description: Classification request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.ClassificationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Successful text classification
          schema:
            $ref: '#/definitions/models.ClassificationResponse'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "429":
          description: Rate limit exceeded
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Classify text
      tags:
      - AI Processing
  /ai/embeddings:
    post:
      consumes:
      - application/json
      description: Generate vector embeddings for the given text. Rate limited to
        30 requests per minute per IP address.
      parameters:
      - description: Embeddings request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.EmbeddingsRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Successful embeddings generation
          schema:
            $ref: '#/definitions/models.EmbeddingsResponse'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "429":
          description: Rate limit exceeded
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Generate text embeddings
      tags:
      - AI Processing
  /ai/message:
    post:
      consumes:
      - application/json
      description: Send a message to the AI and get a response. Rate limited to 30
        requests per minute per IP address.
      parameters:
      - description: Message request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.MessageRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Successful response
          schema:
            $ref: '#/definitions/models.MessageResponse'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "429":
          description: Rate limit exceeded
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Process a message
      tags:
      - AI Processing
  /ai/model-info:
    get:
      description: Returns detailed information about the current AI model. Rate limited
        to 100 requests per minute per IP address.
      produces:
      - application/json
      responses:
        "200":
          description: Model information
          schema:
            additionalProperties: true
            type: object
        "429":
          description: Rate limit exceeded
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get model information
      tags:
      - Model Info
  /ai/sentiment:
    post:
      consumes:
      - application/json
      description: Analyze the sentiment of the provided text. Rate limited to 30
        requests per minute per IP address.
      parameters:
      - description: Sentiment request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.SentimentRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Successful sentiment analysis
          schema:
            $ref: '#/definitions/models.SentimentResponse'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "429":
          description: Rate limit exceeded
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Analyze sentiment
      tags:
      - AI Processing
  /ai/summarization:
    post:
      consumes:
      - application/json
      description: Generate a summary of the provided text. Rate limited to 30 requests
        per minute per IP address.
      parameters:
      - description: Summarization request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.SummarizationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Successful text summarization
          schema:
            $ref: '#/definitions/models.SummarizationResponse'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "429":
          description: Rate limit exceeded
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Summarize text
      tags:
      - AI Processing
  /health:
    get:
      description: Returns the health status of the AI service. Rate limited to 200
        requests per minute per IP address.
      produces:
      - application/json
      responses:
        "200":
          description: Service is healthy
          schema:
            $ref: '#/definitions/models.HealthResponse'
        "429":
          description: Rate limit exceeded
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Health check
      tags:
      - Health
swagger: "2.0"
